version: "3.9"

services:
  app:
    build: .
    container_name: url_shortener_app
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      MONGO_URI: 
      BASE_URL: localhost:8080
      REDIS_PASSWORD: 
      ENCODING_SECRET: 
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: redis
    command: ["redis-server", "--requirepass", "LrhPWu4hX2Gi3XGbVEb4nXTiPOZXYYB2"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
